"""theme model datatype JSONB

Revision ID: 665bda304a74
Revises: e242861af095
Create Date: 2021-04-14 21:21:26.381246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '665bda304a74'
down_revision = 'e242861af095'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('themes', 'css_styles')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('themes', sa.Column('css_styles', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
