"""add lang and font fields to editor

Revision ID: 85086bf9c04b
Revises: ccebfe0cd4cf
Create Date: 2021-04-17 18:58:59.291452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85086bf9c04b'
down_revision = 'ccebfe0cd4cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('themes', sa.Column('font_type', sa.String(length=80), nullable=True))
    op.add_column('themes', sa.Column('lang', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('themes', 'lang')
    op.drop_column('themes', 'font_type')
    # ### end Alembic commands ###
