"""theme model datatype JSONB for real

Revision ID: ccebfe0cd4cf
Revises: 665bda304a74
Create Date: 2021-04-14 21:22:16.682804

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ccebfe0cd4cf'
down_revision = '665bda304a74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('themes', sa.Column('css_styles', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('themes', 'css_styles')
    # ### end Alembic commands ###
