"""empty message

Revision ID: e242861af095
Revises: eeb653b4efe2
Create Date: 2021-04-12 20:51:54.851768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e242861af095'
down_revision = 'eeb653b4efe2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('theme_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'reviews', 'themes', ['theme_id'], ['id'])
    op.add_column('themes', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'themes', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'themes', type_='foreignkey')
    op.drop_column('themes', 'user_id')
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_column('reviews', 'theme_id')
    # ### end Alembic commands ###
