/* AUTH TYPES */
export const SUBMIT_REGISTRATION = 'SUBMIT_REGISTRATION'
export const SUBMIT_LOGIN = 'SUBMIT_LOGIN'
export const ADD_REGISTRATION = 'ADD_REGISTRATION'
export const ADD_LOGIN = 'ADD_LOGIN'

/* USER TYPES */
export const GET_USERS = 'GET_USERS'
export const GET_USER_BY_ID = 'GET_USER_BY_ID'
export const GET_THEMES_BY_USER = 'GET_THEMES_BY_USER'
export const GET_REVIEWSTHEMES_BY_USER = 'GET_REVIEWSTHEMES_BY_USER'
export const TARGET_USER_ID = 'TARGET_USER_ID'
export const SET_CURRENT_USER = 'SET_CURRENT_USER'

/*  THEME TYPES */
export const GET_THEMES = 'GET_THEMES'
export const GET_THEME_BY_ID = 'GET_THEME_BY_ID'
export const CREATE_THEME = 'CREATE_THEME'
export const INCREMENT_LIKES = 'INCREMENT_LIKES'
export const DELETE_THEME_BY_ID = 'DELETE_THEME_BY_ID'
export const SET_SELECTED_THEME = 'SET_SELECTED_THEME'

/* EDITOR TYPES */
export const ADD_CSS = 'ADD_CSS'
export const CSS_SUBMITTED = 'CSS_SUBMITTED'
export const ADD_META_DETAILS = 'ADD_META_DETAILS'

/* REVIEW TYPES */
export const GET_REVIEWS_BY_THEME = 'GET_REVIEWS_BY_THEME'
export const CREATE_REVIEW = 'CREATE_REVIEW'
export const DELETE_REVIEW = 'DELETE_REVIEW'
export const REVIEW_SUBMITTED = 'REVIEW_SUBMITTED'
export const ADD_REVIEW_INPUT = 'ADD_REVIEW_INPUT'
